# postgres-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXNzCg== # base64 encoded 'postgrespassword'
  POSTGRES_USER: cG9zdGdyZXM= # base64 encoded 'postgres'
  POSTGRES_DB: cG9zdGdyZXNkYg== # base64 encoded 'postgresdb'
